# Generated by Django 4.2.6 on 2024-08-02 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='ip_address',
        ),
    ]
